name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest

      - name: Build debug APK
        run: ./gradlew assembleDebug

      - name: Start emulator
        run: |
          echo "y" | sdkmanager --install "system-images;android-30;default;x86_64"
          echo "no" | avdmanager create avd -n test -k "system-images;android-30;default;x86_64" --force
          emulator -avd test -no-audio -no-window -no-boot-anim &
          adb wait-for-device
          adb shell input keyevent 82

      - name: Run instrumented tests
        run: ./gradlew connectedDebugAndroidTest



